# Generated by Django 3.0.4 on 2020-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_state', models.CharField(max_length=100, null=True)),
                ('country_region', models.CharField(max_length=100, null=True)),
                ('last_update', models.CharField(max_length=100, null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('confirmed', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('recovered', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['object_id'],
            },
        ),
    ]
